name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release  

    # Uncomment the below when tests are ready
    # - name: Run tests
    #   run: dotnet test --no-build --verbosity normal

    - name: Run application in Debug mode
      run: dotnet run --no-build --configuration Debug --project SmaHauJenHoaVij/SmaHauJenHoaVij.csproj
